version: '3'
services:
  buildtest:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c 'deno task build'
    ports:
      - 1993:1993
    stdin_open: true
    tty: true
  vitest:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c 'deno task test watch'
    stdin_open: true
    tty: true
